# Generated by Django 5.2.10 on 2026-08-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('lesson', models.TextField()),
                ('post_to_facebook', models.BooleanField(default=False, verbose_name='Facebook')),
                ('post_to_instagram', models.BooleanField(default=False, verbose_name='Instagram')),
                ('post_to_linkedin', models.BooleanField(default=False, verbose_name='LinkedIn')),
                ('post_to_tiktok', models.BooleanField(default=False, verbose_name='TikTok')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('request_image', models.BooleanField(default=False, verbose_name='Request Image With Post')),
                ('generated_content', models.JSONField(blank=True, default=dict)),
                ('generation_status', models.CharField(default='pending', max_length=20)),
                ('generation_error', models.TextField(blank=True)),
            ],
        ),
    ]
