# Generated by Django 5.2.10 on 2026-08-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_topic', models.CharField(max_length=300)),
                ('question1', models.CharField(editable=False, max_length=300)),
                ('answer1', models.TextField()),
                ('question2', models.CharField(editable=False, max_length=300)),
                ('answer2', models.TextField()),
                ('question3', models.CharField(editable=False, max_length=300)),
                ('answer3', models.TextField()),
                ('question4', models.CharField(editable=False, max_length=300)),
                ('answer4', models.TextField()),
                ('question5', models.CharField(editable=False, max_length=300)),
                ('answer5', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lesson_description', models.TextField()),
                ('suggested_topics', models.JSONField(blank=True, editable=False, null=True)),
                ('generation_error', models.TextField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('blog_questions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.blogquestions')),
            ],
        ),
        migrations.AddField(
            model_name='blogquestions',
            name='topic_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_questions', to='blog.topic'),
        ),
    ]
