# Generated by Django 5.2.10 on 2026-08-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogquestions',
            name='principle',
            field=models.TextField(blank=True),
        ),
    ]
